#include "script_local.h"

struct Script_AST * Script_AST_append(struct Script_AST_Allocator * allocator, struct Script_AST * list, struct Script_AST * item);
struct Script_AST * Script_AST_prepend(struct Script_AST_Allocator * allocator, struct Script_AST * list, struct Script_AST * item);
struct Script_AST * Script_AST_declaration(struct Script_AST_Allocator * allocator, const char * name, struct Script_AST * type, struct Script_AST * value);
struct Script_AST * Script_AST_binding(struct Script_AST_Allocator * allocator, const char * name, struct Script_AST * value);
struct Script_AST * Script_AST_if(struct Script_AST_Allocator * allocator, const char * let_name, struct Script_AST * let_value, struct Script_AST * test, struct Script_AST * block, struct Script_AST * elif);
struct Script_AST * Script_AST_elif(struct Script_AST_Allocator * allocator, const char * let_name, struct Script_AST * let_value, struct Script_AST * test, struct Script_AST * block, struct Script_AST * elif);
struct Script_AST * Script_AST_while(struct Script_AST_Allocator * allocator, const char * let_name, struct Script_AST * let_value, struct Script_AST * test, struct Script_AST * block, struct Script_AST * else_block);
struct Script_AST * Script_AST_assign(struct Script_AST_Allocator * allocator, struct Script_AST * target, int op, struct Script_AST * value);
struct Script_AST * Script_AST_return(struct Script_AST_Allocator * allocator, struct Script_AST * expr);
struct Script_AST * Script_AST_break(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_continue(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_deref(struct Script_AST_Allocator * allocator, struct Script_AST * item);
struct Script_AST * Script_AST_ref(struct Script_AST_Allocator * allocator, struct Script_AST * item);
struct Script_AST * Script_AST_number_negate(struct Script_AST_Allocator * allocator, struct Script_AST * item);
struct Script_AST * Script_AST_number_conjugate(struct Script_AST_Allocator * allocator, struct Script_AST * item);
struct Script_AST * Script_AST_bit_negate(struct Script_AST_Allocator * allocator, struct Script_AST * item);
struct Script_AST * Script_AST_array_access(struct Script_AST_Allocator * allocator, struct Script_AST * left, struct Script_AST * index);
struct Script_AST * Script_AST_call(struct Script_AST_Allocator * allocator, struct Script_AST * left, struct Script_AST * arguments);
struct Script_AST * Script_AST_member_access(struct Script_AST_Allocator * allocator, struct Script_AST * left, const char *);
struct Script_AST * Script_AST_annotation(struct Script_AST_Allocator * allocator, struct Script_AST * value, struct Script_AST * type);
struct Script_AST * Script_AST_structure_type(struct Script_AST_Allocator * allocator, struct Script_AST * members);
struct Script_AST * Script_AST_structure_value(struct Script_AST_Allocator * allocator, struct Script_AST * values, struct Script_AST * from);
struct Script_AST * Script_AST_enum_type(struct Script_AST_Allocator * allocator, struct Script_AST * members);
struct Script_AST * Script_AST_enum_value(struct Script_AST_Allocator * allocator, const char * option, struct Script_AST * value);
struct Script_AST * Script_AST_function_type(struct Script_AST_Allocator * allocator, struct Script_AST * arguments, struct Script_AST * result);
struct Script_AST * Script_AST_function_value(struct Script_AST_Allocator * allocator, struct Script_AST * arguments, struct Script_AST * block);
struct Script_AST * Script_AST_extract_names(struct Script_AST_Allocator * allocator, struct Script_AST * arguments);
struct Script_AST * Script_AST_tuple_type(struct Script_AST_Allocator * allocator, struct Script_AST * types);
struct Script_AST * Script_AST_tuple_value(struct Script_AST_Allocator * allocator, struct Script_AST * types);
struct Script_AST * Script_AST_string(struct Script_AST_Allocator * allocator, const char *);
struct Script_AST * Script_AST_char_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_void(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_bool(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_true(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_false(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_character(struct Script_AST_Allocator * allocator, const char *);
struct Script_AST * Script_AST_name(struct Script_AST_Allocator * allocator, const char *);
struct Script_AST * Script_AST_number(struct Script_AST_Allocator * allocator, const char *);
struct Script_AST * Script_AST_uint_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_u8_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_u8_value(struct Script_AST_Allocator * allocator, const char *);
struct Script_AST * Script_AST_u16_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_u16_value(struct Script_AST_Allocator * allocator, const char *);
struct Script_AST * Script_AST_u32_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_u32_value(struct Script_AST_Allocator * allocator, const char *);
struct Script_AST * Script_AST_u64_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_u64_value(struct Script_AST_Allocator * allocator, const char *);
struct Script_AST * Script_AST_int_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_i8_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_i8_value(struct Script_AST_Allocator * allocator, const char *);
struct Script_AST * Script_AST_i16_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_i16_value(struct Script_AST_Allocator * allocator, const char *);
struct Script_AST * Script_AST_i32_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_i32_value(struct Script_AST_Allocator * allocator, const char *);
struct Script_AST * Script_AST_i64_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_i64_value(struct Script_AST_Allocator * allocator, const char *);
struct Script_AST * Script_AST_real_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_f32_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_f32_value(struct Script_AST_Allocator * allocator, const char *);
struct Script_AST * Script_AST_f64_type(struct Script_AST_Allocator * allocator);
struct Script_AST * Script_AST_f64_value(struct Script_AST_Allocator * allocator, const char *);

